name: CMake Build

on:
  push:
    branches: ["dev_server", "dev_client", "feat_updage_cmake", "cross/feat/server"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: g++
        build-type: Release
        parallel: 14

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh

    - name: Install dependencies with vcpkg
      run: |
        ./vcpkg/vcpkg install sfml
        ./vcpkg/vcpkg integrate install

    - name: Configure CMake project
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build project
      run: |
        cmake --build build

    - name: Build Client
      run: |
        cmake --build build --target r-type_client

    - name: Build Server
      run: |
        cmake --build build --target r-type_server