name: CMake Build

on:
  push:
    branches: ["dev_server", "dev_client", "feat_updage_cmake", "cross/feat/server"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build & Test
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ runner.workspace }}/build
        cc: gcc
        cxx: g++
        build-type: Release
        parallel: 14