name: CMake on multiple platforms

on:
  push:
    branches: ["dev_server", "dev_client", "feat_updage_cmake", "cross/feat/server"]
  pull_request:
    branches: ["dev", "main", "feat_updage_cmake"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Release ]
        c_compiler: [ gcc, clang, cl ]
        cpp_compiler: [ g++, clang++, cl ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl
          - os: ubuntu-latest
            cpp_compiler: cl

    steps:
    - uses: actions/checkout@v4

    - name: Install system dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libudev-dev \
          libgl1-mesa-dev

    - name: Clone vcpkg
      run: git clone https://github.com/microsoft/vcpkg.git

    - name: Set VCPKG_ROOT environment variable
      run: |
        echo "VCPKG_ROOT_UBUNTU=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV
        echo "VCPKG_ROOT_WIN=${{ github.workspace }}\\vcpkg" >> $GITHUB_ENV

    - name: Install SFML with vcpkg Windows
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
          ${{ github.workspace }}\vcpkg\bootstrap-vcpkg.bat
          ${{ github.workspace }}\vcpkg\vcpkg.exe install sfml:x64-windows

    - name: Install SFML with vcpkg ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh
          ${{ github.workspace }}/vcpkg/vcpkg install sfml

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} \
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
        -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT_UBUNTU }}/scripts/buildsystems/vcpkg.cmake \
        -S ${{ github.workspace }}

    - name: Configure CMake (Windows)
      if: matrix.os == 'windows-latest'
      shell: pwsh
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} `
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} `
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} `
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
        -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake" `
        -G "Visual Studio 17 2022" `
        -S ${{ github.workspace }}
    

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}